url: www.bre.tc
paginate: 3 
permalink: pretty
markdown: rdiscount
safe: true
lsi: false
pygments: true

author: "Bret Comnes"
description: "A Personal Website and Blog"
location: "Portland, OR"
brand: "&#916;"
marker: "&rarr;"

recent_posts: 10