url: bret.io
paginate: 10
permalink: pretty
markdown: rdiscount
safe: true
lsi: false
highlighter: pygments
port: 4000
future: true
exclude: [categories.html, Gemfile, Gemfile.lock, README.md, vendor, cache.manifest]
include: [".well-known"]

source:      .
destination: ./_site
plugins:     ./_plugins

author: "Bret Comnes"
description: "A Personal Website and Blog"
location: "Portland, OR"
brand: "bret.io"  # This is displays in the navbar
permalink_marker: "&#916;"  # This is the permalink marker.
linklog: "&#8620;"	# This is the little indicator next to link-log posts
ownyourgram: "/media/ownyourgram/"

recent_posts: 10

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # or pages
    values:
      layout: "entry"
gems:
#- jekyll-mentions
- jemoji
- jekyll-redirect-from

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url: http://bret.io

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

